apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "argocd-extensions-pod-files.fullname" . }}
  labels:
    {{- include "argocd-extensions-pod-files.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
  - apiGroups:
      - ""
    resources:
      - pods/exec
    verbs:
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "argocd-extensions-pod-files.fullname" . }}
  labels:
    {{- include "argocd-extensions-pod-files.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "argocd-extensions-pod-files.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "argocd-extensions-pod-files.fullname" . }}
